wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.1
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687004705.531024
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.10.1
      5: 0.15.2
      6: 4.29.0
      8:
      - 3
      - 5
